theme: jekyll-theme-cayman
collections:
  terms:
    output: true
    permalink: /:collection/:title
    
defaults:
  - scope:
      path: ""
      type: terms
    values:
      layout: default    

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-titles-from-headings
