theme: jekyll-theme-cayman
collections:
  terms:
    output: true
    permalink: :path/:title
defaults:
  - scope:
      path: "/terms/"
      type: terms
    values:
      layout: page
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-titles-from-headings
